(function(p){p(window,"undefined"===typeof window._acic?{}:window._acic,"undefined"===typeof window._aci_action?null:window._aci_action,"undefined"===typeof window._aci_debug?!1:window._aci_debug)})(function(p,m,l,v){function f(){if(!(this instanceof f))return new f;this.version="0.1.1";this.urlHit="//www.acint.net/hit/";this.urlAct="//www.acint.net/act/";this.urlJump="//www.acint.net/jump/";this.urlPing="//www.acint.net/ping/";this.urlMatchCookie="//www.acint.net/mc/";this.urlRid="//dsp-rtb.sape.ru/getrid/";
this.cookieName="aid";this.cookieValueOptOut="opt-out";this.uid="";this.presence={timeouts:[3E3,2E4],nofRequests:0};this.dspTrack={timeout:50,maxNofRequests:4,nofRequests:0,ready:!1,bidRequestId:""};this.action={timeout:500,timeoutEmpty:2E3,countPerCycle:3,index:0,methods:{register:"register"},userCanReset:["timeout","timeoutEmpty","countPerCycle"]};this.config={dataProvider:"",allowExtLinksTrack:!0,allowPresenceTrack:!0,allowCookieMatch:!0,allowDspTrack:!1,customData:null,action:null}}var r=!!v,
t={};"object"==typeof JSON&&"function"==typeof JSON.stringify?t.stringify=function(a){return JSON.stringify(a)}:function(){function a(a){function b(a){return 10>a?"0"+a:a}if(a&&"object"==typeof a){if(a instanceof Date)return isFinite(a.valueOf())?a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"Z":null;if(a instanceof String||a instanceof Number||a instanceof Boolean)return a.valueOf()}return a}function c(a){h.lastIndex=
0;return h.test(a)?'"'+a.replace(h,function(a){var b=u[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(h,u){var f,s,l,m,p=e,q,n=u[h],n=a(n);"function"===typeof k&&(n=k.call(u,h,n));switch(typeof n){case "string":return c(n);case "number":return isFinite(n)?String(n):"null";case "boolean":case "null":return String(n);case "object":if(!n)return"null";e+=d;q=[];if("[object Array]"===Object.prototype.toString.apply(n)){m=n.length;for(f=0;f<
m;f+=1)q[f]=b(f,n)||"null";l=0===q.length?"[]":e?"[\n"+e+q.join(",\n"+e)+"\n"+p+"]":"["+q.join(",")+"]";e=p;return l}if(k&&"object"===typeof k)for(m=k.length,f=0;f<m;f+=1)s=k[f],"string"===typeof s&&(l=b(s,n))&&q.push(c(s)+(e?": ":":")+l);else for(s in n)Object.prototype.hasOwnProperty.call(n,s)&&(l=b(s,n))&&q.push(c(s)+(e?": ":":")+l);l=0===q.length?"{}":e?"{\n"+e+q.join(",\n"+e)+"\n"+p+"}":"{"+q.join(",")+"}";e=p;return l}}var h,e,d,u,k;"function"!==typeof t.stringify&&(h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
u={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},t.stringify=function(a,c,h){var f;d=e="";if("number"===typeof h)for(f=0;f<h;f+=1)d+=" ";else"string"===typeof h&&(d=h);if((k=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSONStub.stringify");return b("",{"":a})})}();var d={generateUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"==a?c:c&3|8).toString(16)}).toLowerCase()},
stringTrimLimit:function(a){if(null==a)return"";a=a.replace(/\s+/gmi," ").replace(/^\s+|\s+$/g,"");1E3<a.length&&(a=a.substr(0,1E3));return a},padInt:function(a){return 10>a?"0"+a:""+a},getTimeZoneOffsetIso8601:function(){var a=(new Date).getTimezoneOffset();return(0<a?"-":"+")+this.padInt(Math.floor(Math.abs(a)/60))+":"+this.padInt(Math.abs(a)%60)},getDateTimeIso8601:function(a){var c=new Date;return c.getFullYear()+"-"+this.padInt(c.getMonth()+1)+"-"+this.padInt(c.getDate())+"T"+this.padInt(c.getHours())+
":"+this.padInt(c.getMinutes())+":"+this.padInt(c.getSeconds())+"."+String((c.getMilliseconds()/1E3).toFixed(3)).slice(2,5)+(!0===a?this.getTimeZoneOffsetIso8601:"")},isObject:function(a){return"object"===typeof a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"undefined"!==typeof Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},isEmptyObject:function(a){for(var c in a)return!1;return!0},isString:function(a){return"string"===typeof a||
a instanceof String},encodeUriParam:function(a){if(null==a)return"";a=""+a;return encodeURIComponent instanceof Function?encodeURIComponent(a):escape(a)},implodeUriParams:function(a){var c,b=[];for(c in a)a.hasOwnProperty(c)&&b.push(c+"="+a[c]);return b.join("&")},makeRequestUri:function(a,c){var b=d.implodeUriParams(c);8E3<b.length&&(b=b.substr(0,8E3));return a+"?"+b},makeRequestImage:function(a,c){var b=window.Image?new Image:document.createElement("img");b.src=a;c&&document.body.appendChild(b)},
makeRequestScript:function(a){var c=document.createElement("script");c&&(c.setAttribute("src",a),document.body.appendChild(c))},makeRequestIframe:function(a){var c=document.createElement("iframe");c&&(c.setAttribute("src",a),c.setAttribute("style","width:1px;height:1px;display:none;"),c.setAttribute("frameBorder","0"),c.setAttribute("width","0"),c.setAttribute("height","0"),document.body.appendChild(c))},addReadOnlyProperty:function(a,c,b){Object.defineProperty(a,c,{value:b,writeable:!1,enumerable:!0,
configurable:!1})},addEventListenerCrossBrowser:function(a,c,b){if(a.addEventListener)a.addEventListener(c,b,!1);else if(a.attachEvent)a.attachEvent("on"+c,b);else throw"Cannot add event listener: no Event API support in client";},removeEventListenerCrossBrowser:function(a,c,b){if(a.removeEventListener)a.removeEventListener(c,b,!1);else if(a.attachEvent)a.detachEvent("on"+c,b);else throw"Cannot remove event listener: no Event API support in client";},fireEventCrossBrowser:function(a,c){var b,h=document;
if(h.createEvent){var e=null;switch(c){case "click":case "dblclick":case "mousedown":case "mouseup":case "mouseover":case "mousemove":case "mouseout":case "mouseenter":case "mouseleave":e="MouseEvent";break;case "wheel":e="WheelEvent";break;case "load":case "unload":case "abort":case "error":case "select":case "resize":case "scroll":e="UIEvent";break;case "focus":case "focusin":case "focusout":case "blur":e="FocusEvent";break;case "beforeinput":case "input":e="InputEvent";break;case "keydown":case "keyup":e=
"KeyboardEvent";break;case "compositionstart":case "compositionupdate":case "compositionend":e="CompositionEvent"}try{b=h.createEvent(e)}catch(d){try{b=h.createEvent("HtmlEvents")}catch(f){try{b=h.createEvent("Event")}catch(k){throw Error("Cannot create event object for specified event: "+c);}}}b.initEvent(c,!0,!1);a.dispatchEvent(b)}else if(h.createEventObject)b=h.createEventObject(),b.eventType=c,a.fireEvent("on"+c,b);else if("function"==typeof a["on"+c])a["on"+c]()},fireSameEventCrosBrowser:function(a,
c,b){var h=document,e;if(h.createEvent)try{e=new b.constructor(c,b),a.dispatchEvent(e)}catch(d){e=h.createEvent("MouseEvent"),e.initMouseEvent(b.type,!0,!0,window,0,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget||null),a.dispatchEvent(e)}else if(h.createEventObject)e=h.createEventObject(b),e.eventType=c,a.fireEvent("on"+c,e);else if("function"==typeof a["on"+c])a["on"+c]()},bindOnReady:function(a){function c(){h||(h=!0,a())}function b(){if(!h)try{f.doScroll("left"),
c()}catch(a){setTimeout(b,10)}}var h=!1,e=window,d=document,f=d.documentElement;if(d.addEventListener)d.addEventListener("DOMContentLoaded",c,!1);else if(d.attachEvent){try{var k=null!=e.frameElement}catch(l){}f.doScroll&&!k&&b();d.attachEvent("onreadystatechange",function(){"complete"===d.readyState&&c()})}else if(e.addEventListener)e.addEventListener("load",c,!1);else if(e.attachEvent)e.attachEvent("onload",c);else{var m=e.onload;e.onload=function(){m&&m();c()}}},cookies:{getItem:function(a){return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+
encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null},setItem:function(a,c,b,d,e,g){if(!a||/^(?:expires|max\-age|path|domain|secure)$/i.test(a))return!1;var f="";if(b)switch(b.constructor){case Number:f=Infinity===b?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":"; max-age="+b;break;case String:f="; expires="+b;break;case Date:f="; expires="+b.toUTCString()}document.cookie=encodeURIComponent(a)+"="+encodeURIComponent(c)+f+(e?"; domain="+e:"")+(d?"; path="+d:"")+
(g?"; secure":"");return!0},removeItem:function(a,c,b){if(!a||!this.hasItem(a))return!1;document.cookie=encodeURIComponent(a)+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(b?"; domain="+b:"")+(c?"; path="+c:"");return!0},hasItem:function(a){return(new RegExp("(?:^|;\\s*)"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie)},keys:function(){for(var a=document.cookie.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/),c=
0;c<a.length;c++)a[c]=decodeURIComponent(a[c]);return a}}};f.prototype.init=function(){if(!(this.isAlreadyLoaded()||d.cookies.hasItem(this.cookieName)&&this.cookieValueOptOut==d.cookies.getItem(this.cookieName))){this.uid=d.generateUUID();this.parseConfig();var a=this,c=function(){a.initHit();!0===a.config.allowCookieMatch&&a.initCookieMatch();!0===a.config.allowExtLinksTrack&&a.initExtLinksTrack();!0===a.config.allowPresenceTrack&&a.initPresenceTrack();a.initActionCycle()};if(!0===this.config.allowDspTrack){this.initDspTrack();
var b=function(){!1===a.dspTrack.ready&&a.dspTrack.nofRequests<a.dspTrack.maxNofRequests?(a.dspTrack.nofRequests++,setTimeout(b,a.dspTrack.timeout)):c()};b()}else c()}};f.prototype.initHit=function(){var a=d.makeRequestUri(this.urlHit,this.collectDataOnInit());d.makeRequestImage(a,r)};f.prototype.initActionCycle=function(a){if(void 0===a&&this.config.action){var c=this.config.action,b=this.action,d;if("string"===typeof c&&"{"===c[0])try{c=JSON.parse(c)}catch(e){c={}}for(d=0;d<b.userCanReset.length;d++){var g=
b.userCanReset[d];c.hasOwnProperty(g)&&(b[g]=c[g])}r&&l&&(l.owner_id?console.log("acint: aci_action.owner_id is ["+l.owner_id+"]"):console.warn("acint: aci_action.owner_id is not defined!"))}var f=this;setTimeout(function(){f.processActionData()},a||0)};f.prototype.processActionData=function(){var a=this.action;!l&&p._aci_action&&(l=p._aci_action);if(l&&d.isArray(l)){if(l.length){for(var c=0;a.index<l.length;){var b=l[a.index];a.index++;if("object"===typeof b&&b.hasOwnProperty("length"))if(b.length)for(var h=
0;h<b.length;h++)this.processAction(b[h]),c++;else this.processAction(void 0),c++;else this.processAction(b),c++;if(c>=a.countPerCycle)break}r&&c&&console.log(d.getDateTimeIso8601(!1)+": processed "+c+" actions")}this.initActionCycle(a.timeout)}else r&&console.log(d.getDateTimeIso8601(!1)+": no _aci_action"),a.timeoutEmpty&&(this.initActionCycle(a.timeoutEmpty),a.timeoutEmpty=0)};f.prototype.processAction=function(a){var c=this.action;switch(typeof a){case "function":a="#function";break;case "undefined":a=
"#undefined"}a={owner_id:l.owner_id?l.owner_id:null,action:a};var b=this.collectDataOnAction();b.ad=d.encodeUriParam(d.stringTrimLimit(t.stringify(a)));null!==this.config.customData&&(b.cd=d.encodeUriParam(d.stringTrimLimit(this.config.customData)));c=d.makeRequestUri(this.urlAct+c.methods.register,b);d.makeRequestImage(c,r)};f.prototype.initCookieMatch=function(){var a=d.makeRequestUri(this.urlMatchCookie,this.collectDataOnCookieMatch());d.makeRequestIframe(a)};f.prototype.initExtLinksTrack=function(){var a=
this,c=document,b=function(b){var c=window,g=!1,f;b=b||c.event;var k=b.target||b.srcElement,l=k;if(!("tagName"in k&&"a"==k.tagName.toLowerCase())){for(g=k.parentNode;g;){if("tagName"in g&&"a"==g.tagName.toLowerCase()){f=g;break}if("parentNode"in g)g=g.parentNode;else break}if(f)k=f;else return}if("href"in k&&/^(http:|https:|)\/\/.+/.test(k.href)&&!("hostname"in k&&k.hostname===c.location.hostname)){if(b.shiftKey||b.altKey||b.ctrlKey||b.metaKey)g=!0;g=!0;k.hasOwnProperty("_delayClick")?!1===k.hasOwnProperty("_canSkipDelay")?
"preventDefault"in b?b.preventDefault():b.returnValue=!1:(delete k._canSkipDelay,delete k._delayClick):(c=d.makeRequestUri(a.urlJump,a.collectDataOnClick(b,k)),d.makeRequestImage(c,r),!1===g&&(k._delayClick=!0,setTimeout(function(){k._canSkipDelay=!0;d.fireSameEventCrosBrowser(l,"click",b)},200),"preventDefault"in b?b.preventDefault():b.returnValue=!1))}};"interactive"==c.readyState||"complete"==c.readyState?d.addEventListenerCrossBrowser(c.body,"click",b):d.bindOnReady(function(){d.addEventListenerCrossBrowser(c.body,
"click",b)})};f.prototype.initPresenceTrack=function(){var a=this,c=function(){var b=d.makeRequestUri(a.urlPing,a.collectDataOnPresencePing());d.makeRequestImage(b,r);a.presence.nofRequests+=1;a.presence.nofRequests<a.presence.timeouts.length&&setTimeout(c,a.presence.timeouts[a.presence.nofRequests])};setTimeout(c,this.presence.timeouts[0])};f.prototype.initDspTrack=function(){var a=this,c="cbrid_"+(new Date).getTime();window[c]=function(b){a.dspTrack.bidRequestId=b;a.dspTrack.ready=!0;delete window[c]};
var b=d.makeRequestUri(a.urlRid,{cb:c});d.makeRequestScript(b)};f.prototype.isAlreadyLoaded=function(){if("object"==typeof p._acil&&"function"==typeof p._acil.isLoaded)return!0;"undefined"!==typeof Object.defineProperty?(d.addReadOnlyProperty(p,"_acil",{}),d.addReadOnlyProperty(p._acil,"isLoaded",function(){return!0})):p._acil=function(){return{isLoaded:function(){return!0}}}();return!1};f.prototype.parseConfig=function(){if(d.isObject(m)&&!d.isEmptyObject(m)){var a=["dataProvider"],c=["allowExtLinksTrack",
"allowPresenceTrack","allowCookieMatch","allowDspTrack"],b=["customData"],f=["action"],e,g;for(g=0;g<a.length;g++)e=a[g],m.hasOwnProperty(e)&&(this.config[e]=isNaN(parseInt(m[e],10))?this.config[e]:Math.abs(parseInt(m[e],10)));for(g=0;g<c.length;g++)e=c[g],m.hasOwnProperty(e)&&(this.config[e]=!0===m[e]);for(g=0;g<b.length;g++)if(e=b[g],m.hasOwnProperty(e)&&(a=m[e],!("undefined"===typeof a||null==a||"function"==typeof a||d.isString(a)&&0===a.length||d.isObject(a)&&d.isEmptyObject(a)||d.isArray(a)&&
0===a.length))){try{if(d.isObject(a)||d.isArray(a)){if(a=t.stringify(a),"{}"===a||"[]"===a)a=null}else d.isString(a)||(a=a.toString(),0===a.length&&(a=null))}catch(l){if(a=null,!0===v)throw l;}this.config[e]=a}for(g=0;g<f.length;g++)e=f[g],m.hasOwnProperty(e)&&(this.config[e]=m[e])}};f.prototype.dataAddObligatoryParams=function(a){a.v=this.version;a.uid=this.uid;a.dp=this.config.dataProvider;a.tz=d.encodeUriParam(d.getTimeZoneOffsetIso8601());a.nc=Math.random().toString().substr(2,8);!0===this.config.allowDspTrack&&
(a.brid=d.encodeUriParam(d.stringTrimLimit(this.dspTrack.bidRequestId)));return a};f.prototype.collectDataOnInit=function(){var a=document,c=window,b=this.dataAddObligatoryParams({});b.u=d.encodeUriParam(d.stringTrimLimit(c.location.href));b.r=d.encodeUriParam(d.stringTrimLimit(a.referrer||""));b.rs=c.screen.width+"x"+c.screen.height;b.t=d.encodeUriParam(d.stringTrimLimit(a.title));b.oE=+this.config.allowExtLinksTrack;b.oP=+this.config.allowPresenceTrack;b.dT=d.encodeUriParam(d.getDateTimeIso8601(!1));
null!==this.config.customData&&(b.cd=d.encodeUriParam(d.stringTrimLimit(this.config.customData)));c.parent!==c&&(b["if"]=d.encodeUriParam(c.location.href),b.u=d.encodeUriParam(a.referrer||""),b.r="");return b};f.prototype.collectDataOnCookieMatch=function(){return{dp:this.config.dataProvider}};f.prototype.collectDataOnClick=function(a,c){var b=document,f=window,b=a.target.ownerDocument||b,e=b.documentElement,g=b.body,b=this.dataAddObligatoryParams({});b.u="";b.r="";b.vP="";b.c="";b.aT="";b.hT=0;b.vP=
(f.innerWidth||e.clientWidth||g.clientWidth)+"x"+(f.innerHeight||e.clientHeight||g.clientHeight);null==a.pageX&&null!=a.clientX?b.c=a.clientX+(e&&e.scrollLeft||g&&g.scrollLeft||0)-(e&&e.clientLeft||g&&g.clientLeft||0)+"x"+(a.clientY+(e&&e.scrollTop||g&&g.scrollTop||0)-(e&&e.clientTop||g&&g.clientTop||0)):null!==a.pageX&&(b.c=a.pageX+"x"+a.pageY);b.r=d.encodeUriParam(d.stringTrimLimit(f.location.href));b.u=d.encodeUriParam(d.stringTrimLimit(c.href));var f=c.childNodes,l=0,k=0,m=0;if(1<=f.length){for(e=
0;e<f.length;e++)g=f[e],3!==g.nodeType&&1!==g.nodeType||1!==g.nodeType||(k+=1,"tagName"in f[e]&&"img"===f[e].tagName.toLowerCase()&&(l+=1,m=e));1==l&&l==k?b.hT=1:0<k&&(b.hT=2)}switch(b.hT){case 1:b.aT=f[m].getAttribute("alt")||"";break;case 2:case 0:b.aT=c.innerHTML?c.innerHTML.toString().replace(/<\/?[^>]+>/gmi,""):""}0<b.aT.length&&(b.aT=d.stringTrimLimit(b.aT),""!==b.aT&&(b.aT=/^(\S+(\s|)){1,10}/gmi.exec(b.aT)[0].replace(/^\s+|\s+$/g,"")));b.aT=d.encodeUriParam(b.aT);return b};f.prototype.collectDataOnPresencePing=
function(){var a=this.dataAddObligatoryParams({});a.dT=d.encodeUriParam(d.getDateTimeIso8601(!1));return a};f.prototype.collectDataOnAction=function(a){a||(a={});a=this.dataAddObligatoryParams(a);a.dT=d.encodeUriParam(d.getDateTimeIso8601(!1));return a};try{(new f).init()}catch(w){if(!0===r)throw w;}});
